#!/usr/bin/env bash
# install-watchdog.sh — installs the launchd agent so the bot is auto-restarted
# when it crashes or hangs. Idempotent: re-running just reloads.
#
# What this does (ADR-025):
#   1. Copies scripts/watchdog.sh → ~/bot/bin/watchdog.sh, so launchd's bash
#      doesn't have to read anything in ~/Documents (macOS TCC blocks that).
#   2. Extracts TELEGRAM_BOT_TOKEN + ADMIN_CHAT_IDS from .env and writes them
#      to ~/bot/.watchdog.env (chmod 600), the only config the watchdog reads
#      at runtime.
#   3. Copies the plist to ~/Library/LaunchAgents and bootstraps it.
#
# Uninstall: scripts/uninstall-watchdog.sh

set -euo pipefail

LABEL="com.deepesh.resume-bot-watchdog"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SRC_PLIST="$SCRIPT_DIR/${LABEL}.plist"
SRC_SCRIPT="$SCRIPT_DIR/watchdog.sh"
ENV_FILE="$REPO_ROOT/.env"

DEST_PLIST="$HOME/Library/LaunchAgents/${LABEL}.plist"
DEST_SCRIPT_DIR="$HOME/bot/bin"
DEST_SCRIPT="$DEST_SCRIPT_DIR/watchdog.sh"
DEST_ENV="$HOME/bot/.watchdog.env"

[ -f "$SRC_PLIST" ]  || { echo "source plist missing: $SRC_PLIST"  >&2; exit 1; }
[ -f "$SRC_SCRIPT" ] || { echo "source script missing: $SRC_SCRIPT" >&2; exit 1; }
[ -f "$ENV_FILE" ]   || { echo ".env missing at $ENV_FILE — needed for watchdog DM config" >&2; exit 1; }

echo "==> deploying watchdog script to $DEST_SCRIPT (outside ~/Documents to avoid TCC)"
mkdir -p "$DEST_SCRIPT_DIR"
cp "$SRC_SCRIPT" "$DEST_SCRIPT"
chmod 755 "$DEST_SCRIPT"

echo "==> writing $DEST_ENV with TELEGRAM_BOT_TOKEN + ADMIN_CHAT_IDS"
TOKEN=$(grep -E '^TELEGRAM_BOT_TOKEN=' "$ENV_FILE" | head -1 | cut -d= -f2-)
IDS=$(grep -E '^ADMIN_CHAT_IDS=' "$ENV_FILE" | head -1 | cut -d= -f2-)
if [ -z "$TOKEN" ] || [ -z "$IDS" ]; then
  echo "TELEGRAM_BOT_TOKEN or ADMIN_CHAT_IDS missing/empty in $ENV_FILE" >&2
  exit 1
fi
umask 077
cat > "$DEST_ENV" <<EOF
# Auto-generated by install-watchdog.sh — do not edit by hand.
# Source: $ENV_FILE at install time.
TELEGRAM_BOT_TOKEN=$TOKEN
ADMIN_CHAT_IDS=$IDS
EOF
chmod 600 "$DEST_ENV"

echo "==> copying $SRC_PLIST → $DEST_PLIST"
mkdir -p "$(dirname "$DEST_PLIST")"
cp "$SRC_PLIST" "$DEST_PLIST"

echo "==> bootstrap (load) the agent"
# 'bootout' first to make this idempotent if already loaded.
launchctl bootout "gui/$(id -u)/${LABEL}" 2>/dev/null || true
launchctl bootstrap "gui/$(id -u)" "$DEST_PLIST"

echo "==> kickstart immediately (don't wait for first 2-min interval)"
launchctl kickstart -k "gui/$(id -u)/${LABEL}"

echo "==> status"
launchctl print "gui/$(id -u)/${LABEL}" | grep -E "(state|last exit|program)" | head -10 || true

echo
echo "Watchdog installed. It will:"
echo "  • run every 2 min via launchd"
echo "  • restart the bot if heartbeat is stale (>3 min) or process is gone"
echo "  • DM admin via Telegram on every restart"
echo "  • log to ~/bot/logs/watchdog.log"
echo
echo "Tail watchdog activity:"
echo "  tail -f ~/bot/logs/watchdog.log"
echo
echo "Verify with:"
echo "  launchctl print gui/\$(id -u)/${LABEL} | grep 'last exit'"
echo "  Healthy: 'last exit code = 0'."
echo
echo "Re-run this script after editing scripts/watchdog.sh to redeploy."
echo
echo "Uninstall:"
echo "  bash scripts/uninstall-watchdog.sh"
